### ISSUE TITLE
Renameuser extension throws errors with the GlobalBlocking extension

### ISSUE THREAD

**Issue by Ultracane1997** [Hypoverse/GlobalBlocking#1]
`Renameuser` seems to throw errors when it completes while the `GlobalBlocking` extension is also enabled.

```Original exception: [20c0be2620a997a64fc2063e] /wiki/Special:RenameUser ArgumentCountError: Too few arguments to function MediaWiki\Extension\GlobalBlocking\GlobalRenameHooks::__construct(), 2 passed in /var/www/html/w/vendor/wikimedia/object-factory/src/ObjectFactory.php on line 247 and exactly 3 expected
Backtrace:
from /var/www/html/w/extensions/GlobalBlocking/includes/GlobalRenameHooks.php(30)
#0 /var/www/html/w/vendor/wikimedia/object-factory/src/ObjectFactory.php(247): MediaWiki\Extension\GlobalBlocking\GlobalRenameHooks->__construct()
#1 /var/www/html/w/vendor/wikimedia/object-factory/src/ObjectFactory.php(152): Wikimedia\ObjectFactory\ObjectFactory::getObjectFromSpec()
#2 /var/www/html/w/includes/HookContainer/HookContainer.php(473): Wikimedia\ObjectFactory\ObjectFactory->createObject()
#3 /var/www/html/w/includes/HookContainer/HookContainer.php(156): MediaWiki\HookContainer\HookContainer->getHandlers()
#4 /var/www/html/w/extensions/Renameuser/includes/RenameuserHookRunner.php(38): MediaWiki\HookContainer\HookContainer->run()
#5 /var/www/html/w/extensions/Renameuser/includes/RenameuserSQL.php(336): MediaWiki\Extension\Renameuser\RenameuserHookRunner->onRenameUserComplete()
#6 /var/www/html/w/includes/libs/rdbms/database/Database.php(2501): MediaWiki\Extension\Renameuser\RenameuserSQL->MediaWiki\Extension\Renameuser\{closure}()
#7 /var/www/html/w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(1869): Wikimedia\Rdbms\Database->runOnTransactionIdleCallbacks()
#8 /var/www/html/w/includes/libs/rdbms/lbfactory/LBFactory.php(469): Wikimedia\Rdbms\LoadBalancer->runPrimaryTransactionIdleCallbacks()
#9 /var/www/html/w/includes/libs/rdbms/lbfactory/LBFactory.php(424): Wikimedia\Rdbms\LBFactory->executePostTransactionCallbacks()
#10 /var/www/html/w/includes/MediaWiki.php(670): Wikimedia\Rdbms\LBFactory->commitPrimaryChanges()
#11 /var/www/html/w/includes/MediaWiki.php(640): MediaWiki::preOutputCommit()
#12 /var/www/html/w/includes/MediaWiki.php(917): MediaWiki->doPreOutputCommit()
#13 /var/www/html/w/includes/MediaWiki.php(562): MediaWiki->main()
#14 /var/www/html/w/index.php(50): MediaWiki->run()
#15 /var/www/html/w/index.php(46): wfIndexMain()
#16 {main}```

**Comment by Ultracane1997** [comment]
The relevant `Renameuser` files are located [here](https://github.com/Hypoverse/GlobalBlocking/tree/main/Renameuser).

**Comment by Ultracane1997** [comment]
Thanks to @Universal-Omega, we have fixed this issue. It will now be closed.
